language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader wordnet
script: pytest
notifications:
  email:
    - 3innielee@gmail.com
